### ISSUE TITLE
sidebar appearing in video player when full screen

### ISSUE THREAD

**Issue by GhanzidkarGhanzer** [AvalonBar/AvalonBar#16] opened 2024-07-23 18:38 UTC
so if you check "keep the sidebar on top of windows" then in video player in full screen it will appear so i would like for this to be fixed

**Comment by fofajardo** [comment] 2024-07-24 01:13
Thanks for reporting! This is a known issue. Duplicate of #9.

**Closed by fofajardo** 2024-07-24 01:13 UTC

**Comment by GhanzidkarGhanzer** [comment] 2024-07-25 10:13
> Thanks for reporting! This is a known issue. Duplicate of #9.

ok but did you see the another issue i posted
